# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: el

pipeline:
  - name: SpacyNLP
    model: "el_core_news_md"
    case_sensitive: False
  - name: SpacyTokenizer
         # ONLY add those combinations of intents for which you see enough examples coming in from real users.
    intent_tokenization_flag: True
         # Default is underscore "_"
    intent_split_symbol: "+"
  - name: DucklingEntityExtractor
    url: "https://duckling-aegean-solutions.azurewebsites.net/"
    dimensions: ["time"]
    locale: "el_GR"
       # if not set the default timezone of Duckling is going to be used
       # needed to calculate dates from relative expressions like "tomorrow"
    timezone: "Europe/Athens"
  - name: SpacyFeaturizer
    pooling: mean
  - name: RegexFeaturizer
    case_sensitive: False
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 150
    constrain_similarities: True
    use_gpu: true
  - name: SpacyEntityExtractor
    dimensions: ["PERSON"]
       # Note !SOS!: It is not possible to use the SpacyTokenizer + SpacyFeaturizer in
       #       combination with the WhitespaceTokenizer, and as a result the
       #       "PERSON" extraction by Spacy is not very robust.
       #       Because of this, the nlu training data is annotated as well, and the
       #       DIETClassifier will also extract "PERSON" entities .
  - name: EntitySynonymMapper
  - name: RegexEntityExtractor  # <-- make sure this component is present in your pipeline config.
    # text will be processed with case insensitive as default
    case_sensitive: False
    # use lookup tables to extract entities
    use_lookup_tables: True
  - name: FallbackClassifier
    threshold: 0.6
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.6
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
  - name: UnexpecTEDIntentPolicy
    epochs: 200
    use_gpu: true
  - name: TEDPolicy
    epochs: 200
    constrain_similarities: True
    use_gpu: True

assistant_id: infobot-greek
